import mongoose from 'mongoose'
import { connectDB } from '../lib/db/connect'
import Product from '../lib/db/models/Product'

const JACKHERER_IMG = '/strains/jackherer.png'
const CHERRYGASM_IMG = '/strains/cherrygasm.jpeg'
const FLOWER_IMG = '/strains/ODB.png'

const products = [
  // ── GENETICS (seeds) ──────────────────────────────────────────────
  {
    name: 'O.D.B (Old Dirty Biker)',
    slug: 'odb',
    category: 'seed',
    strain: {
      type: 'hybrid',
      genetics: 'UK Exodus Cheese × Biker Kush',
      origin: 'european',
      floweringTime: 66,
      yield: 'high',
      difficulty: 'easy',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '20-24%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'The ODB aka Cheesy Rider was created by popular demand from our customers. We took a legendary Cheese cut and crossed it with our go-to stud, the Biker Kush V1 to create this indica-dominant hybrid cannabis strain.\n\nGrows vigorously with a branchy structure similar to skunk strains. The OG in the genetics helps ODB produce tight, dense buds with a lot of trichome coverage.\n\nThis is a particularly pungent strain, a cheesy hybrid with all the power of OG — this is one for the cheese freaks!',
    shortDescription: 'aka Cheesy Rider. UK Exodus Cheese × Biker Kush — pungent, dense, OG-powered.',
    descriptionCs: 'ODB aka Cheesy Rider vznikl na přání našich zákazníků. Vzali jsme legendární Cheese klon a zkřížili ho s naším oblíbeným samcem, Biker Kush V1, a vznikl tento indica-dominantní hybrid.\n\nRoste energicky s větvovitou strukturou podobnou skunk strainům. OG v genetice pomáhá ODB produkovat pevné, husté pupeny s bohatým pokryvem trichomů.\n\nJe to zvláště aromatický strain — sýrový hybrid se vší silou OG. Tohle je pro milovníky sýrů!',
    shortDescriptionCs: 'aka Cheesy Rider. UK Exodus Cheese × Biker Kush — intenzivní, hustý, OG výkon.',
    price: 80,
    stock: 25,
    images: [JACKHERER_IMG],
    tags: ['european', 'cheese', 'hybrid', 'feminized', 'high-yield', 'pungent'],
    isAvailable: true,
    isFeatured: true,
  },
  {
    name: 'Jack Herer',
    slug: 'jack-herer',
    category: 'seed',
    strain: {
      type: 'sativa',
      genetics: 'Haze x (Northern Lights #5 x Shiva Skunk)',
      origin: 'european',
      floweringTime: 56,
      yield: 'medium',
      difficulty: 'medium',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '18-23%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'Jack Herer® is a sativa-dominant hybrid (55% Sativa / 45% Indica) — officially recognised as one of the few medicinal cannabis strains in the Netherlands. Bred by Sensi Seeds in Holland, it is widely classified simply as a sativa by growers and the community for its effects: energetic, cerebral, and uplifting. Try it once and you\'ll probably never want to smoke anything else.\n\nMost phenotypes show strong sativa growth behaviour coupled with indica-grade resin production. Buds are among the biggest you\'ll ever see — calyxes stack at multiple points, forming enormous structures. Carefully cultivated buds glisten with a thick layer of THC-rich trichomes so dense that under a microscope, the bud appears composed more of resin glands than plant tissue.\n\nReady to harvest in 8 weeks (56 days). Develops a complex aroma once dried: sharp, savoury hashish tones blended with Afghan and fruity skunk notes. A multiple harvest festival winner worldwide.',
    shortDescription: 'Sensi Seeds classic. Cerebral & uplifting, trichome-heavy, hashish & skunk aroma.',
    descriptionCs: 'Jack Herer® je sativa-dominantní hybrid (55 % Sativa / 45 % Indica) — oficiálně uznávaný jako jeden z mála medicinálních cannabis strainů v Nizozemsku. Vyšlechtěn Sensi Seeds v Holandsku, je komunitou řazen jednoduše mezi sativy pro své účinky: energetický, cerebrální a povznášející. Zkus ho jednou a pravděpodobně nikdy nebudeš chtít kouřit nic jiného.\n\nVětšina fenotypů vykazuje silné sativa růstové chování spolu s indica-grade produkcí pryskyřice. Pupeny jsou mezi největšími, jaké uvidíš — kalixy se skládají na více místech a tvoří obrovské struktury. Pečlivě pěstované pupeny se třpytí hustou vrstvou trichomů bohatých na THC, tak hustou, že pod mikroskopem vypadá pupen spíše jako shluklé pryskyřičné žlázy než rostlinná tkáň.\n\nPřipraven ke sklizni za 8 týdnů (56 dní). Po usušení vyvíjí komplexní aroma: ostré, slané tóny hašiše smíchané s afghánskými a ovocnými skunk notami. Vícenásobný vítěz festivalů po celém světě.',
    shortDescriptionCs: 'Klasika Sensi Seeds. Cerebrální a povznášející, plný trichomů, hašiš a skunk.',
    price: 42,
    stock: 30,
    images: [JACKHERER_IMG],
    tags: ['european', 'sativa', 'cup-winner', 'feminized', 'medicinal'],
    isAvailable: true,
    isFeatured: true,
  },
  {
    name: 'Cherrygasm',
    slug: 'cherrygasm',
    category: 'seed',
    strain: {
      type: 'indica',
      genetics: 'Cherry Pie × OG Kush',
      origin: 'usa',
      floweringTime: 58,
      yield: 'high',
      difficulty: 'easy',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '22-26%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'Cherrygasm lives up to the name — dense, frosted colas with a deep cherry and dark berry terpene profile that hits you before you even open the jar. A Cherry Pie × OG Kush cross that inherited the best of both worlds: the OG\'s structural compactness and resin output, the Cherry Pie\'s unmistakable sweet-sour fruit punch. Short 58-day flower time, beginner-tolerant, and a standout performer in coco or light soil mix. Expect vivid purple hues on cool nights and an extremely sticky trim.',
    shortDescription: 'Cherry & dark berry bombs. Dense OG structure, 58-day finish.',
    descriptionCs: 'Cherrygasm naplňuje svůj název — husté, omrzlé coly s hlubokým třešňovým a tmavě bobulím terpenovým profilem, který tě zasáhne ještě dřív, než otevřeš sklenici. Kříženec Cherry Pie × OG Kush, který zdědil to nejlepší z obou světů: kompaktní strukturu a produkci pryskyřice OG a nezaměnitelný sladkokyselý ovocný punch Cherry Pie. Krátká 58denní doba kvetení, tolerantní k začátečníkům, vynikající výkon v coco nebo lehké zemině. Očekávej výrazné fialové tóny při chladnějších nocích a extrémně lepivé střihání.',
    shortDescriptionCs: 'Třešňové a tmavě bobulové bomby. Hustá OG struktura, 58denní sklizeň.',
    price: 52,
    stock: 18,
    images: [CHERRYGASM_IMG],
    tags: ['usa-genetics', 'cherry', 'purple', 'fast-finish', 'feminized'],
    isAvailable: true,
    isFeatured: true,
  },
  {
    name: 'Dosidos',
    slug: 'dosidos',
    category: 'seed',
    strain: {
      type: 'indica',
      genetics: 'Girl Scout Cookies × Face Off OG',
      origin: 'usa',
      floweringTime: 63,
      yield: 'medium',
      difficulty: 'medium',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '24-28%',
      cbd: '<1%',
      cbn: '0.2%',
    },
    description: 'Dosidos is a powerhouse GSC cross that punches well above its weight class. Earthy, floral, and pungent — the terpene profile is complex and unmistakable. Dense buds covered in a thick trichome layer that makes harvest a satisfying mess. Responds well to topping and LST. Not the easiest strain for beginners but the yield quality and bag appeal make the extra attention worthwhile.',
    shortDescription: 'GSC × Face Off OG. Earthy & floral, trichome-heavy, worth the effort.',
    descriptionCs: 'Dosidos je výkonný kříženec GSC, který výrazně překonává svou váhovou kategorii. Zemitý, květinový a aromatický — terpenový profil je komplexní a nezaměnitelný. Husté pupeny pokryté silnou vrstvou trichomů, díky nimž je sklizeň uspokojivě lepivá. Dobře reaguje na topping a LST. Není nejsnadnější pro začátečníky, ale kvalita sklizně a atraktivní vzhled pupenů za extra péči rozhodně stojí.',
    shortDescriptionCs: 'GSC × Face Off OG. Zemitý a květinový, plný trichomů, stojí za to.',
    price: 50,
    stock: 20,
    images: [JACKHERER_IMG],
    tags: ['usa-genetics', 'gsc', 'indica', 'feminized'],
    isAvailable: true,
    isFeatured: false,
  },
  {
    name: 'Milky Dreams',
    slug: 'milky-dreams',
    category: 'seed',
    strain: {
      type: 'hybrid',
      genetics: 'Cookies & Cream × Wedding Cake',
      origin: 'usa',
      floweringTime: 62,
      yield: 'high',
      difficulty: 'easy',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '23-27%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'Milky Dreams is the ultimate dessert strain — creamy vanilla, sweet dough, and a subtle floral finish. A Cookies & Cream × Wedding Cake cross that stacks colas like a pro and fills the room with an unmistakably sweet fragrance in the final two weeks. Forgiving structure, high trichome output, and a fast-finishing profile that makes it one of the most complete commercial cultivars in the lineup.',
    shortDescription: 'Vanilla & sweet dough terps. Stacking colas, beginner-friendly hybrid.',
    descriptionCs: 'Milky Dreams je ultimátní dezertní strain — krémová vanilka, sladké těsto a jemný květinový závěr. Kříženec Cookies & Cream × Wedding Cake, který stohuje coly jako profesionál a v posledních dvou týdnech naplní místnost nezaměnitelnou sladkou vůní. Odpouštějící struktura, vysoká produkce trichomů a rychlý profil z něj dělají jeden z nejkompletnějších kultivarů v nabídce.',
    shortDescriptionCs: 'Vanilka a sladké těsto. Stohující coly, začátečníkům přívětivý hybrid.',
    price: 46,
    stock: 35,
    images: [JACKHERER_IMG],
    tags: ['usa-genetics', 'dessert-terps', 'hybrid', 'feminized', 'high-yield'],
    isAvailable: true,
    isFeatured: false,
  },
  {
    name: 'Tarte Tarin',
    slug: 'tarte-tarin',
    category: 'seed',
    strain: {
      type: 'hybrid',
      genetics: 'Caramel × Tropicana Cookies',
      origin: 'european',
      floweringTime: 65,
      yield: 'medium',
      difficulty: 'medium',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '19-22%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'Inspired by the French upside-down pastry, Tarte Tarin is a European-bred hybrid with a caramelised fruit and citrus terpene profile that stands apart from the typical USA dessert strains. Caramel sweetness layered over tropical citrus, with a warm amber finish. Medium-sized colas with excellent resin coverage. A refined choice for growers who want something unique on their shelf.',
    shortDescription: 'Caramel & tropical citrus. European hybrid with refined, warm terps.',
    descriptionCs: 'Inspirován francouzským dezertním koláčem, Tarte Tarin je evropsky šlechtěný hybrid s karamelizovaným ovocným a citrusovým terpenovým profilem, který se odlišuje od typických amerických dezertních strainů. Karamelová sladkost vrstvená přes tropické citrusy s teplým jantarovým závěrem. Středně velké coly s vynikajícím pokryvem pryskyřice. Rafinovaná volba pro pěstitele, kteří chtějí něco unikátního na své polici.',
    shortDescriptionCs: 'Karamel a tropické citrusy. Evropský hybrid s rafinovanými, teplými terpy.',
    price: 44,
    stock: 22,
    images: [JACKHERER_IMG],
    tags: ['european', 'hybrid', 'caramel', 'feminized'],
    isAvailable: true,
    isFeatured: false,
  },
  {
    name: 'Velvet Moon',
    slug: 'velvet-moon',
    category: 'seed',
    strain: {
      type: 'indica',
      genetics: 'Purple Punch × Black Cherry Pie',
      origin: 'usa',
      floweringTime: 56,
      yield: 'medium',
      difficulty: 'easy',
      seedType: 'feminized',
      climate: 'indoor',
      thc: '20-24%',
      cbd: '<1%',
      cbn: '0.1%',
    },
    description: 'Velvet Moon is a deep purple indica with a terpene profile built around dark grape, black cherry, and a smooth earthy finish. Purple Punch × Black Cherry Pie — two of the best purple producers in USA genetics — combined into a fast-finishing, visually stunning cultivar. The colour expression under cooler temperatures is remarkable. One of the best strains in the lineup for aesthetic and aroma combined.',
    shortDescription: 'Dark grape & cherry. Stunning purple expression, 56-day fast finish.',
    descriptionCs: 'Velvet Moon je hluboce fialová indica s terpenovým profilem postaveným na tmavém hroznu, černé třešni a hladkém zemitém závěru. Purple Punch × Black Cherry Pie — dva nejlepší fialové producenti v americké genetice — spojeni do rychle kvetoucího, vizuálně ohromujícího kultivaru. Výraz barvy při nižších teplotách je pozoruhodný. Jeden z nejlepších strainů v nabídce pro kombinaci estetiky a aroma.',
    shortDescriptionCs: 'Tmavé hrozno a černá třešeň. Úchvatný fialový výraz, 56denní sklizeň.',
    price: 54,
    stock: 15,
    images: [JACKHERER_IMG],
    tags: ['usa-genetics', 'purple', 'indica', 'feminized', 'fast-finish'],
    isAvailable: true,
    isFeatured: true,
  },

  // ── FLOWERS ──────────────────────────────────────────────────────
  {
    name: 'O.D.B (Old Dirty Biker)',
    slug: 'odb-flower',
    category: 'flower',
    strain: {
      type: 'hybrid',
      genetics: 'UK Exodus Cheese × Biker Kush',
      origin: 'european',
      floweringTime: null,
      yield: null,
      difficulty: null,
      seedType: null,
      climate: 'indoor',
      terpenes: 'Myrcene, Caryophyllene, Limonene',
      thc: '22-25%',
      cbd: '0.8%',
      cbn: '0.2%',
    },
    description: 'The ODB aka Cheesy Rider was created by popular demand from our customers. We took a legendary Cheese cut and crossed it with our go-to stud, the Biker Kush V1 to create this indica-dominant hybrid cannabis strain.\n\nGrows vigorously with a branchy structure similar to skunk strains. The OG in the genetics helps ODB produce tight, dense buds with a lot of trichome coverage.\n\nThis is a particularly pungent strain, a cheesy hybrid with all the power of OG — this is one for the cheese freaks!',
    shortDescription: 'aka Cheesy Rider. UK Exodus Cheese × Biker Kush — pungent, dense, OG-powered.',
    descriptionCs: 'ODB aka Cheesy Rider vznikl na přání našich zákazníků. Vzali jsme legendární Cheese klon a zkřížili ho s naším oblíbeným samcem, Biker Kush V1, a vznikl tento indica-dominantní hybrid.\n\nRoste energicky s větvovitou strukturou podobnou skunk strainům. OG v genetice pomáhá ODB produkovat pevné, husté pupeny s bohatým pokryvem trichomů.\n\nJe to zvláště aromatický strain — sýrový hybrid se vší silou OG. Tohle je pro milovníky sýrů!',
    shortDescriptionCs: 'aka Cheesy Rider. UK Exodus Cheese × Biker Kush — intenzivní, hustý, OG výkon.',
    price: 16,
    stock: 40,
    images: [FLOWER_IMG],
    tags: ['cbd', 'flower', 'indoor', 'hemp', 'cheese', 'european'],
    isAvailable: true,
    isFeatured: false,
  },
  {
    name: 'Jack Herer',
    slug: 'jack-herer-flower',
    category: 'flower',
    strain: {
      type: 'sativa',
      genetics: 'Haze x (Northern Lights #5 x Shiva Skunk)',
      origin: 'european',
      floweringTime: null,
      yield: null,
      difficulty: null,
      seedType: null,
      climate: 'indoor',
      terpenes: 'Terpinolene, Ocimene, Myrcene',
      thc: '20-23%',
      cbd: '0.5%',
      cbn: '0.1%',
    },
    description: 'Jack Herer® is a sativa-dominant hybrid (55% Sativa / 45% Indica) — officially recognised as one of the few medicinal cannabis strains in the Netherlands. Bred by Sensi Seeds in Holland, it\'s widely called a true sativa for its effects: energetic, cerebral, and uplifting. The high is long-lasting, felt in both mind and body — a focused cerebral buzz underpinned by a smooth body warmth.\n\nBuds are among the biggest you\'ll encounter — enormous trichome-covered structures that glisten with resin. So dense with resin glands that under a microscope, the bud appears composed more of trichomes than plant tissue. Diamond-dusted appearance maintained in the dried flower.\n\nComplex aroma: sharp, savoury hashish tones blended with Afghan and fruity skunk notes. A multiple harvest festival winner worldwide — the benchmark European sativa.',
    shortDescription: 'Sensi Seeds classic. Energetic & cerebral, trichome-drenched, hashish & skunk aroma.',
    descriptionCs: 'Jack Herer® je sativa-dominantní hybrid (55 % Sativa / 45 % Indica) — oficiálně uznávaný jako jeden z mála medicinálních cannabis strainů v Nizozemsku. Vyšlechtěn Sensi Seeds v Holandsku, je komunitou označován za pravou sativu pro své účinky: energetický, cerebrální a povznášející. High je dlouhotrvající, pocítíš ho v mysli i těle — soustředěný cerebrální náboj podpořený hladkou tělesnou teplem.\n\nPupeny jsou mezi největšími, jaké potkáš — obrovské struktury pokryté trichomy třpytící se pryskyřicí. Tak hustě plné pryskyřičných žláz, že pod mikroskopem vypadá pupen více z trichomů než z rostlinné tkáně. Diamantový vzhled zachován i v sušeném květu.\n\nKomplexní aroma: ostré, slané tóny hašiše smíchané s afghánskými a ovocnými skunk notami. Vícenásobný vítěz festivalů — měřítko evropské sativy.',
    shortDescriptionCs: 'Klasika Sensi Seeds. Energetický a cerebrální, plný trichomů, hašiš a skunk.',
    price: 14,
    stock: 50,
    images: [FLOWER_IMG],
    tags: ['cbd', 'flower', 'indoor', 'hemp', 'sativa', 'medicinal', 'jack-herer'],
    isAvailable: true,
    isFeatured: true,
  },
  {
    name: 'Bubba Slush',
    slug: 'bubba-slush-flower',
    category: 'flower',
    strain: {
      type: 'indica',
      genetics: 'Bubba Kush × Blue Slush',
      origin: 'usa',
      floweringTime: null,
      yield: null,
      difficulty: null,
      seedType: null,
      climate: 'indoor',
      terpenes: 'Myrcene, Linalool, Caryophyllene',
      thc: '18-21%',
      cbd: '1.2%',
      cbn: '0.2%',
    },
    description: 'Bubba Slush CBD flower is the most visually striking in the lineup — frosted light-green buds with hints of blue and a terpene profile that combines the classic Bubba Kush earthiness with a cool berry finish from the Blue Slush parentage. Indoor grown, slow-dried, hand-trimmed. Low THC (<0.2%), high CBD. Sold per 3.5g. Certificate of analysis available.',
    shortDescription: 'Frosted indoor CBD flower. Earthy Bubba × cool berry finish, <0.2% THC.',
    descriptionCs: 'Bubba Slush CBD květ je vizuálně nejpůsobivější v nabídce — mrazivé světle zelené pupeny s náznaky modré a terpenovým profilem, který kombinuje klasickou zemitost Bubba Kush s chladným bobulím závěrem z Blue Slush rodičovství. Pěstováno uvnitř, pomalu sušeno, ručně stříháno. Nízký THC (<0,2 %), vysoký CBD. Prodáváno po 3,5 g. Certifikát analýzy k dispozici.',
    shortDescriptionCs: 'Mrazivý indoor CBD květ. Zemitý Bubba × chladný bobulový závěr, <0,2 % THC.',
    price: 18,
    stock: 30,
    images: [FLOWER_IMG],
    tags: ['cbd', 'flower', 'indoor', 'hemp', 'lab-tested', 'bubba-kush'],
    isAvailable: true,
    isFeatured: false,
  },

  // ── MERCH ─────────────────────────────────────────────────────────
  {
    name: 'H&S Logo Tee',
    slug: 'hs-logo-tee',
    category: 'merch',
    strain: {
      type: null,
      genetics: '',
      origin: null,
      floweringTime: null,
      yield: null,
      difficulty: null,
      seedType: null,
      climate: null,
    },
    description: 'Heavy 300gsm organic cotton tee. Screen-printed with the H&S cannabis leaf mark in teal on a washed black base. Relaxed unisex cut, pre-shrunk. Printed and shipped from within the EU. Sizes: S / M / L / XL / XXL.',
    shortDescription: 'Washed black organic cotton, teal H&S leaf mark, 300gsm.',
    descriptionCs: 'Těžké organické bavlněné tričko 300 gsm. Sítotiskem potaženo H&S listem konopí v tyrkysové barvě na praném černém základě. Relaxovaný unisex střih, předsrážené. Tištěno a odesíláno z EU. Velikosti: S / M / L / XL / XXL.',
    shortDescriptionCs: 'Prané černé organické bavlněné, tyrkysový H&S list, 300 gsm.',
    price: 34,
    stock: 100,
    images: ['/merch/tshirt.jpg'],
    tags: ['merch', 'organic', 'unisex', 'eu-shipping'],
    isAvailable: true,
    isFeatured: false,
  },
  {
    name: 'Stash Bag — Jack Herer',
    slug: 'stash-bag-jack-herer',
    category: 'merch',
    strain: {
      type: null,
      genetics: '',
      origin: null,
      floweringTime: null,
      yield: null,
      difficulty: null,
      seedType: null,
      climate: null,
    },
    description: 'A premium smell-proof stash bag with the Jack Herer strain art printed on the exterior. Double-zip carbon-lined interior with a velvet inner pouch. Compact enough for a pocket, spacious enough for your essentials. Matte black exterior with teal H&S branding detail. Limited collab drop — Jack Herer edition only.',
    shortDescription: 'Smell-proof carbon-lined stash bag. Jack Herer edition, teal H&S detail.',
    descriptionCs: 'Prémiová bag na úschovu se vzduchotěsným zapínáním a potiskem Jack Herer artworku na povrchu. Dvojité zipování s aktivním uhlím uvnitř a sametovým vnitřním pouzdrem. Dostatečně kompaktní pro kapsu, dostatečně prostorná pro vše důležité. Matný černý exteriér s tyrkysovým H&S brandingem. Limitovaná kolaborační edice — pouze vydání Jack Herer.',
    shortDescriptionCs: 'Vzduchotěsná taška s aktivním uhlím. Edice Jack Herer, tyrkysový H&S detail.',
    price: 22,
    stock: 60,
    images: ['/merch/tshirt.jpg'],
    tags: ['merch', 'stash', 'smell-proof', 'jack-herer', 'limited'],
    isAvailable: true,
    isFeatured: false,
  },
]

async function seed() {
  const force = process.argv.includes('--force')

  console.log('Connecting to MongoDB...')
  await connectDB()

  const existing = await Product.countDocuments()

  if (existing > 0 && !force) {
    console.log(`\n⚠️  Database already has ${existing} products.`)
    console.log('   Seed aborted to protect existing data.')
    console.log('   Run with --force to wipe and re-seed:\n')
    console.log('   pnpm tsx scripts/seed-products.ts --force\n')
    await mongoose.disconnect()
    process.exit(0)
  }

  if (force) {
    console.log('--force passed. Clearing existing products...')
    await Product.deleteMany({})
  }

  console.log(`Seeding ${products.length} products...`)
  const created = await Product.insertMany(products)

  console.log(`✓ Seeded ${created.length} products:`)
  created.forEach((p) => console.log(`  - ${p.name} (${p.slug}) €${p.price}`))

  await mongoose.disconnect()
  console.log('Done.')
}

seed().catch((err) => {
  console.error(err)
  process.exit(1)
})
